from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


class EntityType(str, Enum):
    ARCHITECTURAL_COMPONENT = "ArchitecturalComponent"
    MATERIAL = "Material"
    DEFECT = "Defect"
    EVENT = "Event"
    DYNASTY = "Dynasty"


class RelationType(str, Enum):
    HAS_DEFECT = "hasDefect"
    HAS_MATERIAL = "hasMaterial"
    OCCURRED_AT = "occurredAt"
    AFFECTED = "affected"
    CAUSED_BY = "causedBy"


class Entity(BaseModel):
    id: str = Field(..., description="Entity identifier generated by backend.")
    name: str
    type: EntityType


class Relation(BaseModel):
    source: str = Field(..., description="Source entity name")
    target: str = Field(..., description="Target entity name or time literal")
    type: RelationType


class Triple(BaseModel):
    subject: str
    predicate: RelationType
    object: str


class SourceSummary(BaseModel):
    input_text_chars: int
    image_provided: bool
    pdf_provided: bool
    combined_text_chars: int


class ExtractResponse(BaseModel):
    request_id: str
    model_used: str
    entities: list[Entity]
    relations: list[Relation]
    triples: list[Triple]
    warnings: list[str] = Field(default_factory=list)
    json_output: str
    source_summary: SourceSummary
    debug: dict[str, Any] = Field(default_factory=dict)
